services:
  - type: web
    name: money-docs-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000