services:
  - type: web
    name: money-docs-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000